/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutJobDet implements Serializable {


    @ColumnAlias("CQSHEETID")
    private String cqsheetid;

    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("CLRSEQ")
    private Byte clrseq;

    @ColumnAlias("APVSTS")
    private String apvsts;

    @ColumnAlias("CQREMARK")
    private String cqremark;

    @ColumnAlias("JOBDET")
    private String jobdet;

    public String getCqsheetid() {
        return this.cqsheetid;
    }

    public void setCqsheetid(String cqsheetid) {
        this.cqsheetid = cqsheetid;
    }

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public Byte getClrseq() {
        return this.clrseq;
    }

    public void setClrseq(Byte clrseq) {
        this.clrseq = clrseq;
    }

    public String getApvsts() {
        return this.apvsts;
    }

    public void setApvsts(String apvsts) {
        this.apvsts = apvsts;
    }

    public String getCqremark() {
        return this.cqremark;
    }

    public void setCqremark(String cqremark) {
        this.cqremark = cqremark;
    }

    public String getJobdet() {
        return this.jobdet;
    }

    public void setJobdet(String jobdet) {
        this.jobdet = jobdet;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutJobDet)) return false;
        final ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutJobDet procFd107pk0cqprocGetDetailsAndSheetResponsePoutJobDet = (ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutJobDet) o;
        return Objects.equals(getCqsheetid(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutJobDet.getCqsheetid()) &&
                Objects.equals(getOrdnum(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutJobDet.getOrdnum()) &&
                Objects.equals(getClrseq(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutJobDet.getClrseq()) &&
                Objects.equals(getApvsts(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutJobDet.getApvsts()) &&
                Objects.equals(getCqremark(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutJobDet.getCqremark()) &&
                Objects.equals(getJobdet(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutJobDet.getJobdet());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCqsheetid(),
                getOrdnum(),
                getClrseq(),
                getApvsts(),
                getCqremark(),
                getJobdet());
    }
}