/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd1000wpk0ModjobIsPalletReadyResponsePoutFabseqLov implements Serializable {


    @ColumnAlias("FABSEQ")
    private Byte fabseq;

    @ColumnAlias("FABDESCRIPTION")
    private String fabdescription;

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    public String getFabdescription() {
        return this.fabdescription;
    }

    public void setFabdescription(String fabdescription) {
        this.fabdescription = fabdescription;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd1000wpk0ModjobIsPalletReadyResponsePoutFabseqLov)) return false;
        final ProcFd1000wpk0ModjobIsPalletReadyResponsePoutFabseqLov procFd1000wpk0modjobIsPalletReadyResponsePoutFabseqLov = (ProcFd1000wpk0ModjobIsPalletReadyResponsePoutFabseqLov) o;
        return Objects.equals(getFabseq(), procFd1000wpk0modjobIsPalletReadyResponsePoutFabseqLov.getFabseq()) &&
                Objects.equals(getFabdescription(), procFd1000wpk0modjobIsPalletReadyResponsePoutFabseqLov.getFabdescription());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFabseq(),
                getFabdescription());
    }
}