/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd107pk0CqprocGetLocationListResponse implements Serializable {


    @ColumnAlias("poutLocationList")
    private List<ProcFd107pk0CqprocGetLocationListResponsePoutLocationList> poutLocationList;

    public List<ProcFd107pk0CqprocGetLocationListResponsePoutLocationList> getPoutLocationList() {
        return this.poutLocationList;
    }

    public void setPoutLocationList(List<ProcFd107pk0CqprocGetLocationListResponsePoutLocationList> poutLocationList) {
        this.poutLocationList = poutLocationList;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd107pk0CqprocGetLocationListResponse)) return false;
        final ProcFd107pk0CqprocGetLocationListResponse procFd107pk0cqprocGetLocationListResponse = (ProcFd107pk0CqprocGetLocationListResponse) o;
        return Objects.equals(getPoutLocationList(), procFd107pk0cqprocGetLocationListResponse.getPoutLocationList());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutLocationList());
    }
}