/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd350pk0ModjobGetBatchDetailResponsePoutBatchDetails implements Serializable {


    @ColumnAlias("BCHSEQ")
    private String bchseq;

    @ColumnAlias("PREDYE_BCHWGT")
    private Double predyeBchwgt;

    @ColumnAlias("CANRESET")
    private String canreset;

    @ColumnAlias("BATCHDETAILS")
    private String batchdetails;

    public String getBchseq() {
        return this.bchseq;
    }

    public void setBchseq(String bchseq) {
        this.bchseq = bchseq;
    }

    public Double getPredyeBchwgt() {
        return this.predyeBchwgt;
    }

    public void setPredyeBchwgt(Double predyeBchwgt) {
        this.predyeBchwgt = predyeBchwgt;
    }

    public String getCanreset() {
        return this.canreset;
    }

    public void setCanreset(String canreset) {
        this.canreset = canreset;
    }

    public String getBatchdetails() {
        return this.batchdetails;
    }

    public void setBatchdetails(String batchdetails) {
        this.batchdetails = batchdetails;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd350pk0ModjobGetBatchDetailResponsePoutBatchDetails)) return false;
        final ProcFd350pk0ModjobGetBatchDetailResponsePoutBatchDetails procFd350pk0modjobGetBatchDetailResponsePoutBatchDetails = (ProcFd350pk0ModjobGetBatchDetailResponsePoutBatchDetails) o;
        return Objects.equals(getBchseq(), procFd350pk0modjobGetBatchDetailResponsePoutBatchDetails.getBchseq()) &&
                Objects.equals(getPredyeBchwgt(), procFd350pk0modjobGetBatchDetailResponsePoutBatchDetails.getPredyeBchwgt()) &&
                Objects.equals(getCanreset(), procFd350pk0modjobGetBatchDetailResponsePoutBatchDetails.getCanreset()) &&
                Objects.equals(getBatchdetails(), procFd350pk0modjobGetBatchDetailResponsePoutBatchDetails.getBatchdetails());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getBchseq(),
                getPredyeBchwgt(),
                getCanreset(),
                getBatchdetails());
    }
}