/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd724pk0checkEmpCodeResponse implements Serializable {


    @ColumnAlias("pEmpname")
    private String pempname;

    @ColumnAlias("pEmpcode")
    private String pempcode;

    public String getPempname() {
        return this.pempname;
    }

    public void setPempname(String pempname) {
        this.pempname = pempname;
    }

    public String getPempcode() {
        return this.pempcode;
    }

    public void setPempcode(String pempcode) {
        this.pempcode = pempcode;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd724pk0checkEmpCodeResponse)) return false;
        final ProcFd724pk0checkEmpCodeResponse procFd724pk0checkEmpCodeResponse = (ProcFd724pk0checkEmpCodeResponse) o;
        return Objects.equals(getPempname(), procFd724pk0checkEmpCodeResponse.getPempname()) &&
                Objects.equals(getPempcode(), procFd724pk0checkEmpCodeResponse.getPempcode());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPempname(),
                getPempcode());
    }
}