/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd730wpk0GetMakLcnResponse implements Serializable {


    @ColumnAlias("poutMakLcn")
    private List<ProcFd730wpk0GetMakLcnResponsePoutMakLcn> poutMakLcn;

    public List<ProcFd730wpk0GetMakLcnResponsePoutMakLcn> getPoutMakLcn() {
        return this.poutMakLcn;
    }

    public void setPoutMakLcn(List<ProcFd730wpk0GetMakLcnResponsePoutMakLcn> poutMakLcn) {
        this.poutMakLcn = poutMakLcn;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd730wpk0GetMakLcnResponse)) return false;
        final ProcFd730wpk0GetMakLcnResponse procFd730wpk0getMakLcnResponse = (ProcFd730wpk0GetMakLcnResponse) o;
        return Objects.equals(getPoutMakLcn(), procFd730wpk0getMakLcnResponse.getPoutMakLcn());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutMakLcn());
    }
}