/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd723pk0deliveryOutDetailsResponsePoutMainDestlcnList implements Serializable {


    @ColumnAlias("MAINLCNCOD")
    private String mainlcncod;

    @ColumnAlias("INDEXI")
    private BigInteger indexi;

    public String getMainlcncod() {
        return this.mainlcncod;
    }

    public void setMainlcncod(String mainlcncod) {
        this.mainlcncod = mainlcncod;
    }

    public BigInteger getIndexi() {
        return this.indexi;
    }

    public void setIndexi(BigInteger indexi) {
        this.indexi = indexi;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd723pk0deliveryOutDetailsResponsePoutMainDestlcnList)) return false;
        final ProcFd723pk0deliveryOutDetailsResponsePoutMainDestlcnList procFd723pk0deliveryOutDetailsResponsePoutMainDestlcnList = (ProcFd723pk0deliveryOutDetailsResponsePoutMainDestlcnList) o;
        return Objects.equals(getMainlcncod(), procFd723pk0deliveryOutDetailsResponsePoutMainDestlcnList.getMainlcncod()) &&
                Objects.equals(getIndexi(), procFd723pk0deliveryOutDetailsResponsePoutMainDestlcnList.getIndexi());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getMainlcncod(),
                getIndexi());
    }
}