/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd107pk0CqprocReqSignOffJobListResponsePoutDyejobList implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("FABSEQ")
    private Byte fabseq;

    @ColumnAlias("JOBS")
    private String jobs;

    @ColumnAlias("FABDES")
    private String fabdes;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    public String getJobs() {
        return this.jobs;
    }

    public void setJobs(String jobs) {
        this.jobs = jobs;
    }

    public String getFabdes() {
        return this.fabdes;
    }

    public void setFabdes(String fabdes) {
        this.fabdes = fabdes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd107pk0CqprocReqSignOffJobListResponsePoutDyejobList)) return false;
        final ProcFd107pk0CqprocReqSignOffJobListResponsePoutDyejobList procFd107pk0cqprocReqSignOffJobListResponsePoutDyejobList = (ProcFd107pk0CqprocReqSignOffJobListResponsePoutDyejobList) o;
        return Objects.equals(getOrdnum(), procFd107pk0cqprocReqSignOffJobListResponsePoutDyejobList.getOrdnum()) &&
                Objects.equals(getFabseq(), procFd107pk0cqprocReqSignOffJobListResponsePoutDyejobList.getFabseq()) &&
                Objects.equals(getJobs(), procFd107pk0cqprocReqSignOffJobListResponsePoutDyejobList.getJobs()) &&
                Objects.equals(getFabdes(), procFd107pk0cqprocReqSignOffJobListResponsePoutDyejobList.getFabdes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getFabseq(),
                getJobs(),
                getFabdes());
    }
}