/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd730wpk0GetDeliveryResponsePoutDelList implements Serializable {


    @ColumnAlias("DDELNUM")
    private String ddelnum;

    @ColumnAlias("DESTLCN")
    private String destlcn;

    @ColumnAlias("SRCLCN")
    private String srclcn;

    @ColumnAlias("JOBCOUNT")
    private Short jobcount;

    @ColumnAlias("DESTSCN")
    private String destscn;

    public String getDdelnum() {
        return this.ddelnum;
    }

    public void setDdelnum(String ddelnum) {
        this.ddelnum = ddelnum;
    }

    public String getDestlcn() {
        return this.destlcn;
    }

    public void setDestlcn(String destlcn) {
        this.destlcn = destlcn;
    }

    public String getSrclcn() {
        return this.srclcn;
    }

    public void setSrclcn(String srclcn) {
        this.srclcn = srclcn;
    }

    public Short getJobcount() {
        return this.jobcount;
    }

    public void setJobcount(Short jobcount) {
        this.jobcount = jobcount;
    }

    public String getDestscn() {
        return this.destscn;
    }

    public void setDestscn(String destscn) {
        this.destscn = destscn;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd730wpk0GetDeliveryResponsePoutDelList)) return false;
        final ProcFd730wpk0GetDeliveryResponsePoutDelList procFd730wpk0getDeliveryResponsePoutDelList = (ProcFd730wpk0GetDeliveryResponsePoutDelList) o;
        return Objects.equals(getDdelnum(), procFd730wpk0getDeliveryResponsePoutDelList.getDdelnum()) &&
                Objects.equals(getDestlcn(), procFd730wpk0getDeliveryResponsePoutDelList.getDestlcn()) &&
                Objects.equals(getSrclcn(), procFd730wpk0getDeliveryResponsePoutDelList.getSrclcn()) &&
                Objects.equals(getJobcount(), procFd730wpk0getDeliveryResponsePoutDelList.getJobcount()) &&
                Objects.equals(getDestscn(), procFd730wpk0getDeliveryResponsePoutDelList.getDestscn());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDdelnum(),
                getDestlcn(),
                getSrclcn(),
                getJobcount(),
                getDestscn());
    }
}