/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd1000wpk0ModjobIsPalletReadyResponse implements Serializable {


    @ColumnAlias("pOutIsPalletReady")
    private String poutIsPalletReady;

    @ColumnAlias("pOutJobDetails")
    private List<ProcFd1000wpk0ModjobIsPalletReadyResponsePoutJobDetails> poutJobDetails;

    @ColumnAlias("p_Out_FabseqLOV")
    private List<ProcFd1000wpk0ModjobIsPalletReadyResponsePoutFabseqLov> poutFabseqLov;

    public String getPoutIsPalletReady() {
        return this.poutIsPalletReady;
    }

    public void setPoutIsPalletReady(String poutIsPalletReady) {
        this.poutIsPalletReady = poutIsPalletReady;
    }

    public List<ProcFd1000wpk0ModjobIsPalletReadyResponsePoutJobDetails> getPoutJobDetails() {
        return this.poutJobDetails;
    }

    public void setPoutJobDetails(List<ProcFd1000wpk0ModjobIsPalletReadyResponsePoutJobDetails> poutJobDetails) {
        this.poutJobDetails = poutJobDetails;
    }

    public List<ProcFd1000wpk0ModjobIsPalletReadyResponsePoutFabseqLov> getPoutFabseqLov() {
        return this.poutFabseqLov;
    }

    public void setPoutFabseqLov(List<ProcFd1000wpk0ModjobIsPalletReadyResponsePoutFabseqLov> poutFabseqLov) {
        this.poutFabseqLov = poutFabseqLov;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd1000wpk0ModjobIsPalletReadyResponse)) return false;
        final ProcFd1000wpk0ModjobIsPalletReadyResponse procFd1000wpk0modjobIsPalletReadyResponse = (ProcFd1000wpk0ModjobIsPalletReadyResponse) o;
        return Objects.equals(getPoutIsPalletReady(), procFd1000wpk0modjobIsPalletReadyResponse.getPoutIsPalletReady()) &&
                Objects.equals(getPoutJobDetails(), procFd1000wpk0modjobIsPalletReadyResponse.getPoutJobDetails()) &&
                Objects.equals(getPoutFabseqLov(), procFd1000wpk0modjobIsPalletReadyResponse.getPoutFabseqLov());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutIsPalletReady(),
                getPoutJobDetails(),
                getPoutFabseqLov());
    }
}