/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd730wpk0GetDeliveryDetResponsePoutDelDetList implements Serializable {


    @ColumnAlias("DDELNUM")
    private String ddelnum;

    @ColumnAlias("DYEJOB")
    private String dyejob;

    @ColumnAlias("FABSEQ")
    private Byte fabseq;

    @ColumnAlias("REDYE")
    private Byte redye;

    @ColumnAlias("MODID")
    private String modid;

    @ColumnAlias("MODDAT")
    private LocalDateTime moddat;

    @ColumnAlias("FABTYP")
    private String fabtyp;

    public String getDdelnum() {
        return this.ddelnum;
    }

    public void setDdelnum(String ddelnum) {
        this.ddelnum = ddelnum;
    }

    public String getDyejob() {
        return this.dyejob;
    }

    public void setDyejob(String dyejob) {
        this.dyejob = dyejob;
    }

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    public Byte getRedye() {
        return this.redye;
    }

    public void setRedye(Byte redye) {
        this.redye = redye;
    }

    public String getModid() {
        return this.modid;
    }

    public void setModid(String modid) {
        this.modid = modid;
    }

    public LocalDateTime getModdat() {
        return this.moddat;
    }

    public void setModdat(LocalDateTime moddat) {
        this.moddat = moddat;
    }

    public String getFabtyp() {
        return this.fabtyp;
    }

    public void setFabtyp(String fabtyp) {
        this.fabtyp = fabtyp;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd730wpk0GetDeliveryDetResponsePoutDelDetList)) return false;
        final ProcFd730wpk0GetDeliveryDetResponsePoutDelDetList procFd730wpk0getDeliveryDetResponsePoutDelDetList = (ProcFd730wpk0GetDeliveryDetResponsePoutDelDetList) o;
        return Objects.equals(getDdelnum(), procFd730wpk0getDeliveryDetResponsePoutDelDetList.getDdelnum()) &&
                Objects.equals(getDyejob(), procFd730wpk0getDeliveryDetResponsePoutDelDetList.getDyejob()) &&
                Objects.equals(getFabseq(), procFd730wpk0getDeliveryDetResponsePoutDelDetList.getFabseq()) &&
                Objects.equals(getRedye(), procFd730wpk0getDeliveryDetResponsePoutDelDetList.getRedye()) &&
                Objects.equals(getModid(), procFd730wpk0getDeliveryDetResponsePoutDelDetList.getModid()) &&
                Objects.equals(getModdat(), procFd730wpk0getDeliveryDetResponsePoutDelDetList.getModdat()) &&
                Objects.equals(getFabtyp(), procFd730wpk0getDeliveryDetResponsePoutDelDetList.getFabtyp());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDdelnum(),
                getDyejob(),
                getFabseq(),
                getRedye(),
                getModid(),
                getModdat(),
                getFabtyp());
    }
}