/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd800wpk0McsetupsprocUpdTstRsltResponse implements Serializable {


    @ColumnAlias("p_outmsg")
    private String poutmsg;

    public String getPoutmsg() {
        return this.poutmsg;
    }

    public void setPoutmsg(String poutmsg) {
        this.poutmsg = poutmsg;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd800wpk0McsetupsprocUpdTstRsltResponse)) return false;
        final ProcFd800wpk0McsetupsprocUpdTstRsltResponse procFd800wpk0mcsetupsprocUpdTstRsltResponse = (ProcFd800wpk0McsetupsprocUpdTstRsltResponse) o;
        return Objects.equals(getPoutmsg(), procFd800wpk0mcsetupsprocUpdTstRsltResponse.getPoutmsg());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutmsg());
    }
}