/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd730wpk0GetDeliveryResponse implements Serializable {


    @ColumnAlias("poutDelList")
    private List<ProcFd730wpk0GetDeliveryResponsePoutDelList> poutDelList;

    public List<ProcFd730wpk0GetDeliveryResponsePoutDelList> getPoutDelList() {
        return this.poutDelList;
    }

    public void setPoutDelList(List<ProcFd730wpk0GetDeliveryResponsePoutDelList> poutDelList) {
        this.poutDelList = poutDelList;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd730wpk0GetDeliveryResponse)) return false;
        final ProcFd730wpk0GetDeliveryResponse procFd730wpk0getDeliveryResponse = (ProcFd730wpk0GetDeliveryResponse) o;
        return Objects.equals(getPoutDelList(), procFd730wpk0getDeliveryResponse.getPoutDelList());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutDelList());
    }
}