/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd350pk0ModjobGetBatchDetailResponse implements Serializable {


    @ColumnAlias("poutBatchDetails")
    private List<ProcFd350pk0ModjobGetBatchDetailResponsePoutBatchDetails> poutBatchDetails;

    public List<ProcFd350pk0ModjobGetBatchDetailResponsePoutBatchDetails> getPoutBatchDetails() {
        return this.poutBatchDetails;
    }

    public void setPoutBatchDetails(List<ProcFd350pk0ModjobGetBatchDetailResponsePoutBatchDetails> poutBatchDetails) {
        this.poutBatchDetails = poutBatchDetails;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd350pk0ModjobGetBatchDetailResponse)) return false;
        final ProcFd350pk0ModjobGetBatchDetailResponse procFd350pk0modjobGetBatchDetailResponse = (ProcFd350pk0ModjobGetBatchDetailResponse) o;
        return Objects.equals(getPoutBatchDetails(), procFd350pk0modjobGetBatchDetailResponse.getPoutBatchDetails());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutBatchDetails());
    }
}