/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd730wpk0GetMakLcnResponsePoutMakLcn implements Serializable {


    @ColumnAlias("MAKLCN")
    private String maklcn;

    public String getMaklcn() {
        return this.maklcn;
    }

    public void setMaklcn(String maklcn) {
        this.maklcn = maklcn;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd730wpk0GetMakLcnResponsePoutMakLcn)) return false;
        final ProcFd730wpk0GetMakLcnResponsePoutMakLcn procFd730wpk0getMakLcnResponsePoutMakLcn = (ProcFd730wpk0GetMakLcnResponsePoutMakLcn) o;
        return Objects.equals(getMaklcn(), procFd730wpk0getMakLcnResponsePoutMakLcn.getMaklcn());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getMaklcn());
    }
}