/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd107pk0CqprocReqSignOffJobListResponse implements Serializable {


    @ColumnAlias("poutDeffabseq")
    private Integer poutDeffabseq;

    @ColumnAlias("poutDyejobList")
    private List<ProcFd107pk0CqprocReqSignOffJobListResponsePoutDyejobList> poutDyejobList;

    @ColumnAlias("poutDefDyejob")
    private String poutDefDyejob;

    public Integer getPoutDeffabseq() {
        return this.poutDeffabseq;
    }

    public void setPoutDeffabseq(Integer poutDeffabseq) {
        this.poutDeffabseq = poutDeffabseq;
    }

    public List<ProcFd107pk0CqprocReqSignOffJobListResponsePoutDyejobList> getPoutDyejobList() {
        return this.poutDyejobList;
    }

    public void setPoutDyejobList(List<ProcFd107pk0CqprocReqSignOffJobListResponsePoutDyejobList> poutDyejobList) {
        this.poutDyejobList = poutDyejobList;
    }

    public String getPoutDefDyejob() {
        return this.poutDefDyejob;
    }

    public void setPoutDefDyejob(String poutDefDyejob) {
        this.poutDefDyejob = poutDefDyejob;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd107pk0CqprocReqSignOffJobListResponse)) return false;
        final ProcFd107pk0CqprocReqSignOffJobListResponse procFd107pk0cqprocReqSignOffJobListResponse = (ProcFd107pk0CqprocReqSignOffJobListResponse) o;
        return Objects.equals(getPoutDeffabseq(), procFd107pk0cqprocReqSignOffJobListResponse.getPoutDeffabseq()) &&
                Objects.equals(getPoutDyejobList(), procFd107pk0cqprocReqSignOffJobListResponse.getPoutDyejobList()) &&
                Objects.equals(getPoutDefDyejob(), procFd107pk0cqprocReqSignOffJobListResponse.getPoutDefDyejob());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutDeffabseq(),
                getPoutDyejobList(),
                getPoutDefDyejob());
    }
}