/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutCondList implements Serializable {


    @ColumnAlias("CQSHEETID")
    private String cqsheetid;

    @ColumnAlias("CQCONDSEQ")
    private Short cqcondseq;

    @ColumnAlias("CQCONDCOD")
    private String cqcondcod;

    @ColumnAlias("ACTVAL")
    private String actval;

    @ColumnAlias("MODID")
    private String modid;

    @ColumnAlias("MODDAT")
    private LocalDateTime moddat;

    @ColumnAlias("QUALDESC")
    private String qualdesc;

    @ColumnAlias("INDEXI")
    private BigInteger indexi;

    @ColumnAlias("CONDTYPE")
    private String condtype;

    @ColumnAlias("CONDVAL")
    private String condval;

    @ColumnAlias("CONDCAT")
    private String condcat;

    public String getCqsheetid() {
        return this.cqsheetid;
    }

    public void setCqsheetid(String cqsheetid) {
        this.cqsheetid = cqsheetid;
    }

    public Short getCqcondseq() {
        return this.cqcondseq;
    }

    public void setCqcondseq(Short cqcondseq) {
        this.cqcondseq = cqcondseq;
    }

    public String getCqcondcod() {
        return this.cqcondcod;
    }

    public void setCqcondcod(String cqcondcod) {
        this.cqcondcod = cqcondcod;
    }

    public String getActval() {
        return this.actval;
    }

    public void setActval(String actval) {
        this.actval = actval;
    }

    public String getModid() {
        return this.modid;
    }

    public void setModid(String modid) {
        this.modid = modid;
    }

    public LocalDateTime getModdat() {
        return this.moddat;
    }

    public void setModdat(LocalDateTime moddat) {
        this.moddat = moddat;
    }

    public String getQualdesc() {
        return this.qualdesc;
    }

    public void setQualdesc(String qualdesc) {
        this.qualdesc = qualdesc;
    }

    public BigInteger getIndexi() {
        return this.indexi;
    }

    public void setIndexi(BigInteger indexi) {
        this.indexi = indexi;
    }

    public String getCondtype() {
        return this.condtype;
    }

    public void setCondtype(String condtype) {
        this.condtype = condtype;
    }

    public String getCondval() {
        return this.condval;
    }

    public void setCondval(String condval) {
        this.condval = condval;
    }

    public String getCondcat() {
        return this.condcat;
    }

    public void setCondcat(String condcat) {
        this.condcat = condcat;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutCondList)) return false;
        final ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutCondList procFd107pk0cqprocGetDetailsAndSheetResponsePoutCondList = (ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutCondList) o;
        return Objects.equals(getCqsheetid(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutCondList.getCqsheetid()) &&
                Objects.equals(getCqcondseq(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutCondList.getCqcondseq()) &&
                Objects.equals(getCqcondcod(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutCondList.getCqcondcod()) &&
                Objects.equals(getActval(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutCondList.getActval()) &&
                Objects.equals(getModid(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutCondList.getModid()) &&
                Objects.equals(getModdat(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutCondList.getModdat()) &&
                Objects.equals(getQualdesc(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutCondList.getQualdesc()) &&
                Objects.equals(getIndexi(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutCondList.getIndexi()) &&
                Objects.equals(getCondtype(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutCondList.getCondtype()) &&
                Objects.equals(getCondval(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutCondList.getCondval()) &&
                Objects.equals(getCondcat(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutCondList.getCondcat());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCqsheetid(),
                getCqcondseq(),
                getCqcondcod(),
                getActval(),
                getModid(),
                getModdat(),
                getQualdesc(),
                getIndexi(),
                getCondtype(),
                getCondval(),
                getCondcat());
    }
}