/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd723pk0deliveryOutDetailsResponse implements Serializable {


    @ColumnAlias("poutDyejobDet")
    private String poutDyejobDet;

    @ColumnAlias("poutFabdet")
    private String poutFabdet;

    @ColumnAlias("poutDefSrclcn")
    private String poutDefSrclcn;

    @ColumnAlias("poutDefDestlcn")
    private String poutDefDestlcn;

    @ColumnAlias("poutDefDsestMainlcn")
    private String poutDefDsestMainlcn;

    @ColumnAlias("poutSrclcnList")
    private List<ProcFd723pk0deliveryOutDetailsResponsePoutSrclcnList> poutSrclcnList;

    @ColumnAlias("poutDestlcnList")
    private List<ProcFd723pk0deliveryOutDetailsResponsePoutDestlcnList> poutDestlcnList;

    @ColumnAlias("poutMainDestlcnList")
    private List<ProcFd723pk0deliveryOutDetailsResponsePoutMainDestlcnList> poutMainDestlcnList;

    @ColumnAlias("poutMsg")
    private String poutMsg;

    public String getPoutDyejobDet() {
        return this.poutDyejobDet;
    }

    public void setPoutDyejobDet(String poutDyejobDet) {
        this.poutDyejobDet = poutDyejobDet;
    }

    public String getPoutFabdet() {
        return this.poutFabdet;
    }

    public void setPoutFabdet(String poutFabdet) {
        this.poutFabdet = poutFabdet;
    }

    public String getPoutDefSrclcn() {
        return this.poutDefSrclcn;
    }

    public void setPoutDefSrclcn(String poutDefSrclcn) {
        this.poutDefSrclcn = poutDefSrclcn;
    }

    public String getPoutDefDestlcn() {
        return this.poutDefDestlcn;
    }

    public void setPoutDefDestlcn(String poutDefDestlcn) {
        this.poutDefDestlcn = poutDefDestlcn;
    }

    public String getPoutDefDsestMainlcn() {
        return this.poutDefDsestMainlcn;
    }

    public void setPoutDefDsestMainlcn(String poutDefDsestMainlcn) {
        this.poutDefDsestMainlcn = poutDefDsestMainlcn;
    }

    public List<ProcFd723pk0deliveryOutDetailsResponsePoutSrclcnList> getPoutSrclcnList() {
        return this.poutSrclcnList;
    }

    public void setPoutSrclcnList(List<ProcFd723pk0deliveryOutDetailsResponsePoutSrclcnList> poutSrclcnList) {
        this.poutSrclcnList = poutSrclcnList;
    }

    public List<ProcFd723pk0deliveryOutDetailsResponsePoutDestlcnList> getPoutDestlcnList() {
        return this.poutDestlcnList;
    }

    public void setPoutDestlcnList(List<ProcFd723pk0deliveryOutDetailsResponsePoutDestlcnList> poutDestlcnList) {
        this.poutDestlcnList = poutDestlcnList;
    }

    public List<ProcFd723pk0deliveryOutDetailsResponsePoutMainDestlcnList> getPoutMainDestlcnList() {
        return this.poutMainDestlcnList;
    }

    public void setPoutMainDestlcnList(List<ProcFd723pk0deliveryOutDetailsResponsePoutMainDestlcnList> poutMainDestlcnList) {
        this.poutMainDestlcnList = poutMainDestlcnList;
    }

    public String getPoutMsg() {
        return this.poutMsg;
    }

    public void setPoutMsg(String poutMsg) {
        this.poutMsg = poutMsg;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd723pk0deliveryOutDetailsResponse)) return false;
        final ProcFd723pk0deliveryOutDetailsResponse procFd723pk0deliveryOutDetailsResponse = (ProcFd723pk0deliveryOutDetailsResponse) o;
        return Objects.equals(getPoutDyejobDet(), procFd723pk0deliveryOutDetailsResponse.getPoutDyejobDet()) &&
                Objects.equals(getPoutFabdet(), procFd723pk0deliveryOutDetailsResponse.getPoutFabdet()) &&
                Objects.equals(getPoutDefSrclcn(), procFd723pk0deliveryOutDetailsResponse.getPoutDefSrclcn()) &&
                Objects.equals(getPoutDefDestlcn(), procFd723pk0deliveryOutDetailsResponse.getPoutDefDestlcn()) &&
                Objects.equals(getPoutDefDsestMainlcn(), procFd723pk0deliveryOutDetailsResponse.getPoutDefDsestMainlcn()) &&
                Objects.equals(getPoutSrclcnList(), procFd723pk0deliveryOutDetailsResponse.getPoutSrclcnList()) &&
                Objects.equals(getPoutDestlcnList(), procFd723pk0deliveryOutDetailsResponse.getPoutDestlcnList()) &&
                Objects.equals(getPoutMainDestlcnList(), procFd723pk0deliveryOutDetailsResponse.getPoutMainDestlcnList()) &&
                Objects.equals(getPoutMsg(), procFd723pk0deliveryOutDetailsResponse.getPoutMsg());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutDyejobDet(),
                getPoutFabdet(),
                getPoutDefSrclcn(),
                getPoutDefDestlcn(),
                getPoutDefDsestMainlcn(),
                getPoutSrclcnList(),
                getPoutDestlcnList(),
                getPoutMainDestlcnList(),
                getPoutMsg());
    }
}