/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd730wpk0GetDelDestLovResponsePoutDelDestLov implements Serializable {


    @ColumnAlias("LCNCOD")
    private String lcncod;

    @ColumnAlias("LCNDES")
    private String lcndes;

    public String getLcncod() {
        return this.lcncod;
    }

    public void setLcncod(String lcncod) {
        this.lcncod = lcncod;
    }

    public String getLcndes() {
        return this.lcndes;
    }

    public void setLcndes(String lcndes) {
        this.lcndes = lcndes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd730wpk0GetDelDestLovResponsePoutDelDestLov)) return false;
        final ProcFd730wpk0GetDelDestLovResponsePoutDelDestLov procFd730wpk0getDelDestLovResponsePoutDelDestLov = (ProcFd730wpk0GetDelDestLovResponsePoutDelDestLov) o;
        return Objects.equals(getLcncod(), procFd730wpk0getDelDestLovResponsePoutDelDestLov.getLcncod()) &&
                Objects.equals(getLcndes(), procFd730wpk0getDelDestLovResponsePoutDelDestLov.getLcndes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getLcncod(),
                getLcndes());
    }
}