/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd723pk0deliveryOutDetailsResponsePoutDestlcnList implements Serializable {


    @ColumnAlias("DESTLCNCOD")
    private String destlcncod;

    @ColumnAlias("SCNCOD")
    private String scncod;

    @ColumnAlias("MAINLCNCOD")
    private String mainlcncod;

    @ColumnAlias("INDEXI")
    private BigInteger indexi;

    @ColumnAlias("LCNDES")
    private String lcndes;

    public String getDestlcncod() {
        return this.destlcncod;
    }

    public void setDestlcncod(String destlcncod) {
        this.destlcncod = destlcncod;
    }

    public String getScncod() {
        return this.scncod;
    }

    public void setScncod(String scncod) {
        this.scncod = scncod;
    }

    public String getMainlcncod() {
        return this.mainlcncod;
    }

    public void setMainlcncod(String mainlcncod) {
        this.mainlcncod = mainlcncod;
    }

    public BigInteger getIndexi() {
        return this.indexi;
    }

    public void setIndexi(BigInteger indexi) {
        this.indexi = indexi;
    }

    public String getLcndes() {
        return this.lcndes;
    }

    public void setLcndes(String lcndes) {
        this.lcndes = lcndes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd723pk0deliveryOutDetailsResponsePoutDestlcnList)) return false;
        final ProcFd723pk0deliveryOutDetailsResponsePoutDestlcnList procFd723pk0deliveryOutDetailsResponsePoutDestlcnList = (ProcFd723pk0deliveryOutDetailsResponsePoutDestlcnList) o;
        return Objects.equals(getDestlcncod(), procFd723pk0deliveryOutDetailsResponsePoutDestlcnList.getDestlcncod()) &&
                Objects.equals(getScncod(), procFd723pk0deliveryOutDetailsResponsePoutDestlcnList.getScncod()) &&
                Objects.equals(getMainlcncod(), procFd723pk0deliveryOutDetailsResponsePoutDestlcnList.getMainlcncod()) &&
                Objects.equals(getIndexi(), procFd723pk0deliveryOutDetailsResponsePoutDestlcnList.getIndexi()) &&
                Objects.equals(getLcndes(), procFd723pk0deliveryOutDetailsResponsePoutDestlcnList.getLcndes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDestlcncod(),
                getScncod(),
                getMainlcncod(),
                getIndexi(),
                getLcndes());
    }
}