/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd107pk0CqprocCqPendingListResponsePoutPendList implements Serializable {


    @ColumnAlias("CQSHEETID")
    private String cqsheetid;

    @ColumnAlias("DYEJOB")
    private String dyejob;

    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("CLRSEQ")
    private Byte clrseq;

    @ColumnAlias("APVSTS")
    private String apvsts;

    @ColumnAlias("CQREMARK")
    private String cqremark;

    @ColumnAlias("PENDINGDESC")
    private String pendingdesc;

    @ColumnAlias("BARCODE")
    private String barcode;

    @ColumnAlias("CLRDES")
    private String clrdes;

    @ColumnAlias("BCHSEQ")
    private String bchseq;

    @ColumnAlias("PROCESS")
    private String process;

    @ColumnAlias("TBRELDAT")
    private LocalDateTime tbreldat;

    @ColumnAlias("TBRELLDTIME")
    private Double tbrelldtime;

    @ColumnAlias("PNDTRGDAT")
    private LocalDateTime pndtrgdat;

    @ColumnAlias("PNDLDTIME")
    private Double pndldtime;

    @ColumnAlias("PNDBY")
    private String pndby;

    @ColumnAlias("FABSEQ")
    private Byte fabseq;

    @ColumnAlias("FABTYP")
    private String fabtyp;

    @ColumnAlias("FABWGT")
    private Short fabwgt;

    @ColumnAlias("FABCPS")
    private String fabcps;

    @ColumnAlias("INSPREQ")
    private String inspreq;

    public String getCqsheetid() {
        return this.cqsheetid;
    }

    public void setCqsheetid(String cqsheetid) {
        this.cqsheetid = cqsheetid;
    }

    public String getDyejob() {
        return this.dyejob;
    }

    public void setDyejob(String dyejob) {
        this.dyejob = dyejob;
    }

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public Byte getClrseq() {
        return this.clrseq;
    }

    public void setClrseq(Byte clrseq) {
        this.clrseq = clrseq;
    }

    public String getApvsts() {
        return this.apvsts;
    }

    public void setApvsts(String apvsts) {
        this.apvsts = apvsts;
    }

    public String getCqremark() {
        return this.cqremark;
    }

    public void setCqremark(String cqremark) {
        this.cqremark = cqremark;
    }

    public String getPendingdesc() {
        return this.pendingdesc;
    }

    public void setPendingdesc(String pendingdesc) {
        this.pendingdesc = pendingdesc;
    }

    public String getBarcode() {
        return this.barcode;
    }

    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    public String getClrdes() {
        return this.clrdes;
    }

    public void setClrdes(String clrdes) {
        this.clrdes = clrdes;
    }

    public String getBchseq() {
        return this.bchseq;
    }

    public void setBchseq(String bchseq) {
        this.bchseq = bchseq;
    }

    public String getProcess() {
        return this.process;
    }

    public void setProcess(String process) {
        this.process = process;
    }

    public LocalDateTime getTbreldat() {
        return this.tbreldat;
    }

    public void setTbreldat(LocalDateTime tbreldat) {
        this.tbreldat = tbreldat;
    }

    public Double getTbrelldtime() {
        return this.tbrelldtime;
    }

    public void setTbrelldtime(Double tbrelldtime) {
        this.tbrelldtime = tbrelldtime;
    }

    public LocalDateTime getPndtrgdat() {
        return this.pndtrgdat;
    }

    public void setPndtrgdat(LocalDateTime pndtrgdat) {
        this.pndtrgdat = pndtrgdat;
    }

    public Double getPndldtime() {
        return this.pndldtime;
    }

    public void setPndldtime(Double pndldtime) {
        this.pndldtime = pndldtime;
    }

    public String getPndby() {
        return this.pndby;
    }

    public void setPndby(String pndby) {
        this.pndby = pndby;
    }

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    public String getFabtyp() {
        return this.fabtyp;
    }

    public void setFabtyp(String fabtyp) {
        this.fabtyp = fabtyp;
    }

    public Short getFabwgt() {
        return this.fabwgt;
    }

    public void setFabwgt(Short fabwgt) {
        this.fabwgt = fabwgt;
    }

    public String getFabcps() {
        return this.fabcps;
    }

    public void setFabcps(String fabcps) {
        this.fabcps = fabcps;
    }

    public String getInspreq() {
        return this.inspreq;
    }

    public void setInspreq(String inspreq) {
        this.inspreq = inspreq;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd107pk0CqprocCqPendingListResponsePoutPendList)) return false;
        final ProcFd107pk0CqprocCqPendingListResponsePoutPendList procFd107pk0cqprocCqPendingListResponsePoutPendList = (ProcFd107pk0CqprocCqPendingListResponsePoutPendList) o;
        return Objects.equals(getCqsheetid(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getCqsheetid()) &&
                Objects.equals(getDyejob(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getDyejob()) &&
                Objects.equals(getOrdnum(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getOrdnum()) &&
                Objects.equals(getClrseq(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getClrseq()) &&
                Objects.equals(getApvsts(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getApvsts()) &&
                Objects.equals(getCqremark(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getCqremark()) &&
                Objects.equals(getPendingdesc(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getPendingdesc()) &&
                Objects.equals(getBarcode(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getBarcode()) &&
                Objects.equals(getClrdes(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getClrdes()) &&
                Objects.equals(getBchseq(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getBchseq()) &&
                Objects.equals(getProcess(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getProcess()) &&
                Objects.equals(getTbreldat(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getTbreldat()) &&
                Objects.equals(getTbrelldtime(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getTbrelldtime()) &&
                Objects.equals(getPndtrgdat(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getPndtrgdat()) &&
                Objects.equals(getPndldtime(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getPndldtime()) &&
                Objects.equals(getPndby(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getPndby()) &&
                Objects.equals(getFabseq(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getFabseq()) &&
                Objects.equals(getFabtyp(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getFabtyp()) &&
                Objects.equals(getFabwgt(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getFabwgt()) &&
                Objects.equals(getFabcps(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getFabcps()) &&
                Objects.equals(getInspreq(), procFd107pk0cqprocCqPendingListResponsePoutPendList.getInspreq());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCqsheetid(),
                getDyejob(),
                getOrdnum(),
                getClrseq(),
                getApvsts(),
                getCqremark(),
                getPendingdesc(),
                getBarcode(),
                getClrdes(),
                getBchseq(),
                getProcess(),
                getTbreldat(),
                getTbrelldtime(),
                getPndtrgdat(),
                getPndldtime(),
                getPndby(),
                getFabseq(),
                getFabtyp(),
                getFabwgt(),
                getFabcps(),
                getInspreq());
    }
}