/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd800wpk0McsetupsprocGetTestResultsResponsePoutTestresults implements Serializable {


    @ColumnAlias("DYEJOB")
    private String dyejob;

    @ColumnAlias("FABSEQ")
    private BigInteger fabseq;

    @ColumnAlias("REDYE")
    private BigInteger redye;

    @ColumnAlias("PROCESSID")
    private String processid;

    @ColumnAlias("PROCSEQ")
    private BigInteger procseq;

    @ColumnAlias("PROCESS")
    private String process;

    @ColumnAlias("CQCOD")
    private String cqcod;

    @ColumnAlias("CQDESC")
    private String cqdesc;

    @ColumnAlias("MINVAL")
    private Double minval;

    @ColumnAlias("MAXVAL")
    private Double maxval;

    @ColumnAlias("CQSTAGE")
    private String cqstage;

    @ColumnAlias("UOM")
    private String uom;

    @ColumnAlias("ACTVAL")
    private String actval;

    @ColumnAlias("CQID")
    private String cqid;

    @ColumnAlias("CQDAT")
    private LocalDateTime cqdat;

    @ColumnAlias("UPDALW")
    private Double updalw;

    @ColumnAlias("SORTSEQ")
    private Byte sortseq;

    @ColumnAlias("TARGETVAL")
    private String targetval;

    @ColumnAlias("RIBLACE_BARCODE")
    private String riblaceBarcode;

    public String getDyejob() {
        return this.dyejob;
    }

    public void setDyejob(String dyejob) {
        this.dyejob = dyejob;
    }

    public BigInteger getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(BigInteger fabseq) {
        this.fabseq = fabseq;
    }

    public BigInteger getRedye() {
        return this.redye;
    }

    public void setRedye(BigInteger redye) {
        this.redye = redye;
    }

    public String getProcessid() {
        return this.processid;
    }

    public void setProcessid(String processid) {
        this.processid = processid;
    }

    public BigInteger getProcseq() {
        return this.procseq;
    }

    public void setProcseq(BigInteger procseq) {
        this.procseq = procseq;
    }

    public String getProcess() {
        return this.process;
    }

    public void setProcess(String process) {
        this.process = process;
    }

    public String getCqcod() {
        return this.cqcod;
    }

    public void setCqcod(String cqcod) {
        this.cqcod = cqcod;
    }

    public String getCqdesc() {
        return this.cqdesc;
    }

    public void setCqdesc(String cqdesc) {
        this.cqdesc = cqdesc;
    }

    public Double getMinval() {
        return this.minval;
    }

    public void setMinval(Double minval) {
        this.minval = minval;
    }

    public Double getMaxval() {
        return this.maxval;
    }

    public void setMaxval(Double maxval) {
        this.maxval = maxval;
    }

    public String getCqstage() {
        return this.cqstage;
    }

    public void setCqstage(String cqstage) {
        this.cqstage = cqstage;
    }

    public String getUom() {
        return this.uom;
    }

    public void setUom(String uom) {
        this.uom = uom;
    }

    public String getActval() {
        return this.actval;
    }

    public void setActval(String actval) {
        this.actval = actval;
    }

    public String getCqid() {
        return this.cqid;
    }

    public void setCqid(String cqid) {
        this.cqid = cqid;
    }

    public LocalDateTime getCqdat() {
        return this.cqdat;
    }

    public void setCqdat(LocalDateTime cqdat) {
        this.cqdat = cqdat;
    }

    public Double getUpdalw() {
        return this.updalw;
    }

    public void setUpdalw(Double updalw) {
        this.updalw = updalw;
    }

    public Byte getSortseq() {
        return this.sortseq;
    }

    public void setSortseq(Byte sortseq) {
        this.sortseq = sortseq;
    }

    public String getTargetval() {
        return this.targetval;
    }

    public void setTargetval(String targetval) {
        this.targetval = targetval;
    }

    public String getRiblaceBarcode() {
        return this.riblaceBarcode;
    }

    public void setRiblaceBarcode(String riblaceBarcode) {
        this.riblaceBarcode = riblaceBarcode;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd800wpk0McsetupsprocGetTestResultsResponsePoutTestresults)) return false;
        final ProcFd800wpk0McsetupsprocGetTestResultsResponsePoutTestresults procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults = (ProcFd800wpk0McsetupsprocGetTestResultsResponsePoutTestresults) o;
        return Objects.equals(getDyejob(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getDyejob()) &&
                Objects.equals(getFabseq(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getFabseq()) &&
                Objects.equals(getRedye(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getRedye()) &&
                Objects.equals(getProcessid(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getProcessid()) &&
                Objects.equals(getProcseq(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getProcseq()) &&
                Objects.equals(getProcess(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getProcess()) &&
                Objects.equals(getCqcod(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getCqcod()) &&
                Objects.equals(getCqdesc(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getCqdesc()) &&
                Objects.equals(getMinval(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getMinval()) &&
                Objects.equals(getMaxval(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getMaxval()) &&
                Objects.equals(getCqstage(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getCqstage()) &&
                Objects.equals(getUom(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getUom()) &&
                Objects.equals(getActval(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getActval()) &&
                Objects.equals(getCqid(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getCqid()) &&
                Objects.equals(getCqdat(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getCqdat()) &&
                Objects.equals(getUpdalw(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getUpdalw()) &&
                Objects.equals(getSortseq(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getSortseq()) &&
                Objects.equals(getTargetval(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getTargetval()) &&
                Objects.equals(getRiblaceBarcode(), procFd800wpk0mcsetupsprocGetTestResultsResponsePoutTestresults.getRiblaceBarcode());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDyejob(),
                getFabseq(),
                getRedye(),
                getProcessid(),
                getProcseq(),
                getProcess(),
                getCqcod(),
                getCqdesc(),
                getMinval(),
                getMaxval(),
                getCqstage(),
                getUom(),
                getActval(),
                getCqid(),
                getCqdat(),
                getUpdalw(),
                getSortseq(),
                getTargetval(),
                getRiblaceBarcode());
    }
}