/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd107pk0CqprocGetProcessListResponse implements Serializable {


    @ColumnAlias("poutProcesslist")
    private List<ProcFd107pk0CqprocGetProcessListResponsePoutProcesslist> poutProcesslist;

    public List<ProcFd107pk0CqprocGetProcessListResponsePoutProcesslist> getPoutProcesslist() {
        return this.poutProcesslist;
    }

    public void setPoutProcesslist(List<ProcFd107pk0CqprocGetProcessListResponsePoutProcesslist> poutProcesslist) {
        this.poutProcesslist = poutProcesslist;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd107pk0CqprocGetProcessListResponse)) return false;
        final ProcFd107pk0CqprocGetProcessListResponse procFd107pk0cqprocGetProcessListResponse = (ProcFd107pk0CqprocGetProcessListResponse) o;
        return Objects.equals(getPoutProcesslist(), procFd107pk0cqprocGetProcessListResponse.getPoutProcesslist());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutProcesslist());
    }
}