/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Procfd723pk0getJobissueHisResponsePoutIssueList implements Serializable {


    @ColumnAlias("TRGDAT")
    private LocalDateTime trgdat;

    @ColumnAlias("PROCESS")
    private String process;

    @ColumnAlias("APVSTS")
    private String apvsts;

    @ColumnAlias("CQREMARK")
    private String cqremark;

    @ColumnAlias("REQBY")
    private String reqby;

    @ColumnAlias("HLDBY")
    private String hldby;

    @ColumnAlias("SIGNOFFBY")
    private String signoffby;

    public LocalDateTime getTrgdat() {
        return this.trgdat;
    }

    public void setTrgdat(LocalDateTime trgdat) {
        this.trgdat = trgdat;
    }

    public String getProcess() {
        return this.process;
    }

    public void setProcess(String process) {
        this.process = process;
    }

    public String getApvsts() {
        return this.apvsts;
    }

    public void setApvsts(String apvsts) {
        this.apvsts = apvsts;
    }

    public String getCqremark() {
        return this.cqremark;
    }

    public void setCqremark(String cqremark) {
        this.cqremark = cqremark;
    }

    public String getReqby() {
        return this.reqby;
    }

    public void setReqby(String reqby) {
        this.reqby = reqby;
    }

    public String getHldby() {
        return this.hldby;
    }

    public void setHldby(String hldby) {
        this.hldby = hldby;
    }

    public String getSignoffby() {
        return this.signoffby;
    }

    public void setSignoffby(String signoffby) {
        this.signoffby = signoffby;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Procfd723pk0getJobissueHisResponsePoutIssueList)) return false;
        final Procfd723pk0getJobissueHisResponsePoutIssueList procfd723pk0getJobissueHisResponsePoutIssueList = (Procfd723pk0getJobissueHisResponsePoutIssueList) o;
        return Objects.equals(getTrgdat(), procfd723pk0getJobissueHisResponsePoutIssueList.getTrgdat()) &&
                Objects.equals(getProcess(), procfd723pk0getJobissueHisResponsePoutIssueList.getProcess()) &&
                Objects.equals(getApvsts(), procfd723pk0getJobissueHisResponsePoutIssueList.getApvsts()) &&
                Objects.equals(getCqremark(), procfd723pk0getJobissueHisResponsePoutIssueList.getCqremark()) &&
                Objects.equals(getReqby(), procfd723pk0getJobissueHisResponsePoutIssueList.getReqby()) &&
                Objects.equals(getHldby(), procfd723pk0getJobissueHisResponsePoutIssueList.getHldby()) &&
                Objects.equals(getSignoffby(), procfd723pk0getJobissueHisResponsePoutIssueList.getSignoffby());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTrgdat(),
                getProcess(),
                getApvsts(),
                getCqremark(),
                getReqby(),
                getHldby(),
                getSignoffby());
    }
}