/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd730wpk0GetLastLocationResponse implements Serializable {


    @ColumnAlias("poutLastLocation")
    private String poutLastLocation;

    public String getPoutLastLocation() {
        return this.poutLastLocation;
    }

    public void setPoutLastLocation(String poutLastLocation) {
        this.poutLastLocation = poutLastLocation;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd730wpk0GetLastLocationResponse)) return false;
        final ProcFd730wpk0GetLastLocationResponse procFd730wpk0getLastLocationResponse = (ProcFd730wpk0GetLastLocationResponse) o;
        return Objects.equals(getPoutLastLocation(), procFd730wpk0getLastLocationResponse.getPoutLastLocation());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutLastLocation());
    }
}