/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd723pk0deliveryOutDetailsResponsePoutSrclcnList implements Serializable {


    @ColumnAlias("SRCLCNCOD")
    private String srclcncod;

    @ColumnAlias("INDEXI")
    private BigInteger indexi;

    @ColumnAlias("LCNDES")
    private String lcndes;

    public String getSrclcncod() {
        return this.srclcncod;
    }

    public void setSrclcncod(String srclcncod) {
        this.srclcncod = srclcncod;
    }

    public BigInteger getIndexi() {
        return this.indexi;
    }

    public void setIndexi(BigInteger indexi) {
        this.indexi = indexi;
    }

    public String getLcndes() {
        return this.lcndes;
    }

    public void setLcndes(String lcndes) {
        this.lcndes = lcndes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd723pk0deliveryOutDetailsResponsePoutSrclcnList)) return false;
        final ProcFd723pk0deliveryOutDetailsResponsePoutSrclcnList procFd723pk0deliveryOutDetailsResponsePoutSrclcnList = (ProcFd723pk0deliveryOutDetailsResponsePoutSrclcnList) o;
        return Objects.equals(getSrclcncod(), procFd723pk0deliveryOutDetailsResponsePoutSrclcnList.getSrclcncod()) &&
                Objects.equals(getIndexi(), procFd723pk0deliveryOutDetailsResponsePoutSrclcnList.getIndexi()) &&
                Objects.equals(getLcndes(), procFd723pk0deliveryOutDetailsResponsePoutSrclcnList.getLcndes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSrclcncod(),
                getIndexi(),
                getLcndes());
    }
}