/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutPendingReasonList implements Serializable {


    @ColumnAlias("PNDREASONCOD")
    private String pndreasoncod;

    @ColumnAlias("REASONDESC")
    private String reasondesc;

    @ColumnAlias("INDEXI")
    private BigInteger indexi;

    public String getPndreasoncod() {
        return this.pndreasoncod;
    }

    public void setPndreasoncod(String pndreasoncod) {
        this.pndreasoncod = pndreasoncod;
    }

    public String getReasondesc() {
        return this.reasondesc;
    }

    public void setReasondesc(String reasondesc) {
        this.reasondesc = reasondesc;
    }

    public BigInteger getIndexi() {
        return this.indexi;
    }

    public void setIndexi(BigInteger indexi) {
        this.indexi = indexi;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutPendingReasonList)) return false;
        final ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutPendingReasonList procFd107pk0cqprocGetDetailsAndSheetResponsePoutPendingReasonList = (ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutPendingReasonList) o;
        return Objects.equals(getPndreasoncod(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutPendingReasonList.getPndreasoncod()) &&
                Objects.equals(getReasondesc(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutPendingReasonList.getReasondesc()) &&
                Objects.equals(getIndexi(), procFd107pk0cqprocGetDetailsAndSheetResponsePoutPendingReasonList.getIndexi());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPndreasoncod(),
                getReasondesc(),
                getIndexi());
    }
}