/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Procfd723pk0getJobissueHisResponse implements Serializable {


    @ColumnAlias("poutIssueList")
    private List<Procfd723pk0getJobissueHisResponsePoutIssueList> poutIssueList;

    @ColumnAlias("poutMsg")
    private String poutMsg;

    @ColumnAlias("poutProcessCmp")
    private String poutProcessCmp;

    @ColumnAlias("poutProcessDue")
    private String poutProcessDue;

    public List<Procfd723pk0getJobissueHisResponsePoutIssueList> getPoutIssueList() {
        return this.poutIssueList;
    }

    public void setPoutIssueList(List<Procfd723pk0getJobissueHisResponsePoutIssueList> poutIssueList) {
        this.poutIssueList = poutIssueList;
    }

    public String getPoutMsg() {
        return this.poutMsg;
    }

    public void setPoutMsg(String poutMsg) {
        this.poutMsg = poutMsg;
    }

    public String getPoutProcessCmp() {
        return this.poutProcessCmp;
    }

    public void setPoutProcessCmp(String poutProcessCmp) {
        this.poutProcessCmp = poutProcessCmp;
    }

    public String getPoutProcessDue() {
        return this.poutProcessDue;
    }

    public void setPoutProcessDue(String poutProcessDue) {
        this.poutProcessDue = poutProcessDue;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Procfd723pk0getJobissueHisResponse)) return false;
        final Procfd723pk0getJobissueHisResponse procfd723pk0getJobissueHisResponse = (Procfd723pk0getJobissueHisResponse) o;
        return Objects.equals(getPoutIssueList(), procfd723pk0getJobissueHisResponse.getPoutIssueList()) &&
                Objects.equals(getPoutMsg(), procfd723pk0getJobissueHisResponse.getPoutMsg()) &&
                Objects.equals(getPoutProcessCmp(), procfd723pk0getJobissueHisResponse.getPoutProcessCmp()) &&
                Objects.equals(getPoutProcessDue(), procfd723pk0getJobissueHisResponse.getPoutProcessDue());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutIssueList(),
                getPoutMsg(),
                getPoutProcessCmp(),
                getPoutProcessDue());
    }
}