/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd723pk0placementDetailsResponsePoutFabseqlist implements Serializable {


    @ColumnAlias("FABSEQ")
    private Byte fabseq;

    @ColumnAlias("FABDES")
    private String fabdes;

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    public String getFabdes() {
        return this.fabdes;
    }

    public void setFabdes(String fabdes) {
        this.fabdes = fabdes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd723pk0placementDetailsResponsePoutFabseqlist)) return false;
        final ProcFd723pk0placementDetailsResponsePoutFabseqlist procFd723pk0placementDetailsResponsePoutFabseqlist = (ProcFd723pk0placementDetailsResponsePoutFabseqlist) o;
        return Objects.equals(getFabseq(), procFd723pk0placementDetailsResponsePoutFabseqlist.getFabseq()) &&
                Objects.equals(getFabdes(), procFd723pk0placementDetailsResponsePoutFabseqlist.getFabdes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFabseq(),
                getFabdes());
    }
}