/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd723pk0placementDetailsResponsePoutRackbinList implements Serializable {


    @ColumnAlias("RACKBIN")
    private String rackbin;

    @ColumnAlias("INDEXI")
    private BigInteger indexi;

    @ColumnAlias("EXPPARKING")
    private String expparking;

    public String getRackbin() {
        return this.rackbin;
    }

    public void setRackbin(String rackbin) {
        this.rackbin = rackbin;
    }

    public BigInteger getIndexi() {
        return this.indexi;
    }

    public void setIndexi(BigInteger indexi) {
        this.indexi = indexi;
    }

    public String getExpparking() {
        return this.expparking;
    }

    public void setExpparking(String expparking) {
        this.expparking = expparking;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd723pk0placementDetailsResponsePoutRackbinList)) return false;
        final ProcFd723pk0placementDetailsResponsePoutRackbinList procFd723pk0placementDetailsResponsePoutRackbinList = (ProcFd723pk0placementDetailsResponsePoutRackbinList) o;
        return Objects.equals(getRackbin(), procFd723pk0placementDetailsResponsePoutRackbinList.getRackbin()) &&
                Objects.equals(getIndexi(), procFd723pk0placementDetailsResponsePoutRackbinList.getIndexi()) &&
                Objects.equals(getExpparking(), procFd723pk0placementDetailsResponsePoutRackbinList.getExpparking());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getRackbin(),
                getIndexi(),
                getExpparking());
    }
}