/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd723pk0getFabDetailsResponse implements Serializable {


    @ColumnAlias("poutDyejobDet")
    private String poutDyejobDet;

    @ColumnAlias("pouStsDet")
    private String pouStsDet;

    @ColumnAlias("poutAction")
    private String poutAction;

    @ColumnAlias("poutMsg")
    private String poutMsg;

    @ColumnAlias("poutDyejob")
    private String poutDyejob;

    @ColumnAlias("poutFabseq")
    private Integer poutFabseq;

    @ColumnAlias("poutDoubtful")
    private String poutDoubtful;

    public String getPoutDyejobDet() {
        return this.poutDyejobDet;
    }

    public void setPoutDyejobDet(String poutDyejobDet) {
        this.poutDyejobDet = poutDyejobDet;
    }

    public String getPouStsDet() {
        return this.pouStsDet;
    }

    public void setPouStsDet(String pouStsDet) {
        this.pouStsDet = pouStsDet;
    }

    public String getPoutAction() {
        return this.poutAction;
    }

    public void setPoutAction(String poutAction) {
        this.poutAction = poutAction;
    }

    public String getPoutMsg() {
        return this.poutMsg;
    }

    public void setPoutMsg(String poutMsg) {
        this.poutMsg = poutMsg;
    }

    public String getPoutDyejob() {
        return this.poutDyejob;
    }

    public void setPoutDyejob(String poutDyejob) {
        this.poutDyejob = poutDyejob;
    }

    public Integer getPoutFabseq() {
        return this.poutFabseq;
    }

    public void setPoutFabseq(Integer poutFabseq) {
        this.poutFabseq = poutFabseq;
    }

    public String getPoutDoubtful() {
        return this.poutDoubtful;
    }

    public void setPoutDoubtful(String poutDoubtful) {
        this.poutDoubtful = poutDoubtful;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd723pk0getFabDetailsResponse)) return false;
        final ProcFd723pk0getFabDetailsResponse procFd723pk0getFabDetailsResponse = (ProcFd723pk0getFabDetailsResponse) o;
        return Objects.equals(getPoutDyejobDet(), procFd723pk0getFabDetailsResponse.getPoutDyejobDet()) &&
                Objects.equals(getPouStsDet(), procFd723pk0getFabDetailsResponse.getPouStsDet()) &&
                Objects.equals(getPoutAction(), procFd723pk0getFabDetailsResponse.getPoutAction()) &&
                Objects.equals(getPoutMsg(), procFd723pk0getFabDetailsResponse.getPoutMsg()) &&
                Objects.equals(getPoutDyejob(), procFd723pk0getFabDetailsResponse.getPoutDyejob()) &&
                Objects.equals(getPoutFabseq(), procFd723pk0getFabDetailsResponse.getPoutFabseq()) &&
                Objects.equals(getPoutDoubtful(), procFd723pk0getFabDetailsResponse.getPoutDoubtful());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutDyejobDet(),
                getPouStsDet(),
                getPoutAction(),
                getPoutMsg(),
                getPoutDyejob(),
                getPoutFabseq(),
                getPoutDoubtful());
    }
}