/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd724updateScanProcessResponse implements Serializable {


    @ColumnAlias("pOutNextAction")
    private String poutNextAction;

    @ColumnAlias("poutMsg")
    private String poutMsg;

    @ColumnAlias("poutErrmsg")
    private String poutErrmsg;

    public String getPoutNextAction() {
        return this.poutNextAction;
    }

    public void setPoutNextAction(String poutNextAction) {
        this.poutNextAction = poutNextAction;
    }

    public String getPoutMsg() {
        return this.poutMsg;
    }

    public void setPoutMsg(String poutMsg) {
        this.poutMsg = poutMsg;
    }

    public String getPoutErrmsg() {
        return this.poutErrmsg;
    }

    public void setPoutErrmsg(String poutErrmsg) {
        this.poutErrmsg = poutErrmsg;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd724updateScanProcessResponse)) return false;
        final ProcFd724updateScanProcessResponse procFd724updateScanProcessResponse = (ProcFd724updateScanProcessResponse) o;
        return Objects.equals(getPoutNextAction(), procFd724updateScanProcessResponse.getPoutNextAction()) &&
                Objects.equals(getPoutMsg(), procFd724updateScanProcessResponse.getPoutMsg()) &&
                Objects.equals(getPoutErrmsg(), procFd724updateScanProcessResponse.getPoutErrmsg());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutNextAction(),
                getPoutMsg(),
                getPoutErrmsg());
    }
}