/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd107pk0CqprocGetDetailsAndSheetResponse implements Serializable {


    @ColumnAlias("poutJobDet")
    private List<ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutJobDet> poutJobDet;

    @ColumnAlias("poutCondList")
    private List<ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutCondList> poutCondList;

    @ColumnAlias("poutPendingReasonList")
    private List<ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutPendingReasonList> poutPendingReasonList;

    @ColumnAlias("poutDeffabseq")
    private Integer poutDeffabseq;

    @ColumnAlias("poutDeffabdes")
    private String poutDeffabdes;

    @ColumnAlias("poutFabseqlist")
    private List<ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutFabseqlist> poutFabseqlist;

    @ColumnAlias("poutDyejobList")
    private List<ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutDyejobList> poutDyejobList;

    @ColumnAlias("poutDefDyejob")
    private String poutDefDyejob;

    @ColumnAlias("poutProcess")
    private String poutProcess;

    @ColumnAlias("poutStsList")
    private List<ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutStsList> poutStsList;

    @ColumnAlias("poutMsg")
    private String poutMsg;

    public List<ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutJobDet> getPoutJobDet() {
        return this.poutJobDet;
    }

    public void setPoutJobDet(List<ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutJobDet> poutJobDet) {
        this.poutJobDet = poutJobDet;
    }

    public List<ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutCondList> getPoutCondList() {
        return this.poutCondList;
    }

    public void setPoutCondList(List<ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutCondList> poutCondList) {
        this.poutCondList = poutCondList;
    }

    public List<ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutPendingReasonList> getPoutPendingReasonList() {
        return this.poutPendingReasonList;
    }

    public void setPoutPendingReasonList(List<ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutPendingReasonList> poutPendingReasonList) {
        this.poutPendingReasonList = poutPendingReasonList;
    }

    public Integer getPoutDeffabseq() {
        return this.poutDeffabseq;
    }

    public void setPoutDeffabseq(Integer poutDeffabseq) {
        this.poutDeffabseq = poutDeffabseq;
    }

    public String getPoutDeffabdes() {
        return this.poutDeffabdes;
    }

    public void setPoutDeffabdes(String poutDeffabdes) {
        this.poutDeffabdes = poutDeffabdes;
    }

    public List<ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutFabseqlist> getPoutFabseqlist() {
        return this.poutFabseqlist;
    }

    public void setPoutFabseqlist(List<ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutFabseqlist> poutFabseqlist) {
        this.poutFabseqlist = poutFabseqlist;
    }

    public List<ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutDyejobList> getPoutDyejobList() {
        return this.poutDyejobList;
    }

    public void setPoutDyejobList(List<ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutDyejobList> poutDyejobList) {
        this.poutDyejobList = poutDyejobList;
    }

    public String getPoutDefDyejob() {
        return this.poutDefDyejob;
    }

    public void setPoutDefDyejob(String poutDefDyejob) {
        this.poutDefDyejob = poutDefDyejob;
    }

    public String getPoutProcess() {
        return this.poutProcess;
    }

    public void setPoutProcess(String poutProcess) {
        this.poutProcess = poutProcess;
    }

    public List<ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutStsList> getPoutStsList() {
        return this.poutStsList;
    }

    public void setPoutStsList(List<ProcFd107pk0CqprocGetDetailsAndSheetResponsePoutStsList> poutStsList) {
        this.poutStsList = poutStsList;
    }

    public String getPoutMsg() {
        return this.poutMsg;
    }

    public void setPoutMsg(String poutMsg) {
        this.poutMsg = poutMsg;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd107pk0CqprocGetDetailsAndSheetResponse)) return false;
        final ProcFd107pk0CqprocGetDetailsAndSheetResponse procFd107pk0cqprocGetDetailsAndSheetResponse = (ProcFd107pk0CqprocGetDetailsAndSheetResponse) o;
        return Objects.equals(getPoutJobDet(), procFd107pk0cqprocGetDetailsAndSheetResponse.getPoutJobDet()) &&
                Objects.equals(getPoutCondList(), procFd107pk0cqprocGetDetailsAndSheetResponse.getPoutCondList()) &&
                Objects.equals(getPoutPendingReasonList(), procFd107pk0cqprocGetDetailsAndSheetResponse.getPoutPendingReasonList()) &&
                Objects.equals(getPoutDeffabseq(), procFd107pk0cqprocGetDetailsAndSheetResponse.getPoutDeffabseq()) &&
                Objects.equals(getPoutDeffabdes(), procFd107pk0cqprocGetDetailsAndSheetResponse.getPoutDeffabdes()) &&
                Objects.equals(getPoutFabseqlist(), procFd107pk0cqprocGetDetailsAndSheetResponse.getPoutFabseqlist()) &&
                Objects.equals(getPoutDyejobList(), procFd107pk0cqprocGetDetailsAndSheetResponse.getPoutDyejobList()) &&
                Objects.equals(getPoutDefDyejob(), procFd107pk0cqprocGetDetailsAndSheetResponse.getPoutDefDyejob()) &&
                Objects.equals(getPoutProcess(), procFd107pk0cqprocGetDetailsAndSheetResponse.getPoutProcess()) &&
                Objects.equals(getPoutStsList(), procFd107pk0cqprocGetDetailsAndSheetResponse.getPoutStsList()) &&
                Objects.equals(getPoutMsg(), procFd107pk0cqprocGetDetailsAndSheetResponse.getPoutMsg());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutJobDet(),
                getPoutCondList(),
                getPoutPendingReasonList(),
                getPoutDeffabseq(),
                getPoutDeffabdes(),
                getPoutFabseqlist(),
                getPoutDyejobList(),
                getPoutDefDyejob(),
                getPoutProcess(),
                getPoutStsList(),
                getPoutMsg());
    }
}