/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd730wpk0GetDeliveryDetResponse implements Serializable {


    @ColumnAlias("poutDelDetList")
    private List<ProcFd730wpk0GetDeliveryDetResponsePoutDelDetList> poutDelDetList;

    public List<ProcFd730wpk0GetDeliveryDetResponsePoutDelDetList> getPoutDelDetList() {
        return this.poutDelDetList;
    }

    public void setPoutDelDetList(List<ProcFd730wpk0GetDeliveryDetResponsePoutDelDetList> poutDelDetList) {
        this.poutDelDetList = poutDelDetList;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd730wpk0GetDeliveryDetResponse)) return false;
        final ProcFd730wpk0GetDeliveryDetResponse procFd730wpk0getDeliveryDetResponse = (ProcFd730wpk0GetDeliveryDetResponse) o;
        return Objects.equals(getPoutDelDetList(), procFd730wpk0getDeliveryDetResponse.getPoutDelDetList());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutDelDetList());
    }
}