/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd107pk0CqprocCheckUserResponse implements Serializable {


    @ColumnAlias("pOutUserid")
    private String poutUserid;

    public String getPoutUserid() {
        return this.poutUserid;
    }

    public void setPoutUserid(String poutUserid) {
        this.poutUserid = poutUserid;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd107pk0CqprocCheckUserResponse)) return false;
        final ProcFd107pk0CqprocCheckUserResponse procFd107pk0cqprocCheckUserResponse = (ProcFd107pk0CqprocCheckUserResponse) o;
        return Objects.equals(getPoutUserid(), procFd107pk0cqprocCheckUserResponse.getPoutUserid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutUserid());
    }
}