/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcFd723pk0placementDetailsResponse implements Serializable {


    @ColumnAlias("poutDyejobDet")
    private String poutDyejobDet;

    @ColumnAlias("poutFabdet")
    private String poutFabdet;

    @ColumnAlias("poutLcncod")
    private String poutLcncod;

    @ColumnAlias("poutDefFabseq")
    private Integer poutDefFabseq;

    @ColumnAlias("poutDeffabdes")
    private String poutDeffabdes;

    @ColumnAlias("poutRackbinList")
    private List<ProcFd723pk0placementDetailsResponsePoutRackbinList> poutRackbinList;

    @ColumnAlias("poutFabseqlist")
    private List<ProcFd723pk0placementDetailsResponsePoutFabseqlist> poutFabseqlist;

    @ColumnAlias("poutDyejobList")
    private List<ProcFd723pk0placementDetailsResponsePoutDyejobList> poutDyejobList;

    @ColumnAlias("poutDefDyejob")
    private String poutDefDyejob;

    @ColumnAlias("poutMsg")
    private String poutMsg;

    public String getPoutDyejobDet() {
        return this.poutDyejobDet;
    }

    public void setPoutDyejobDet(String poutDyejobDet) {
        this.poutDyejobDet = poutDyejobDet;
    }

    public String getPoutFabdet() {
        return this.poutFabdet;
    }

    public void setPoutFabdet(String poutFabdet) {
        this.poutFabdet = poutFabdet;
    }

    public String getPoutLcncod() {
        return this.poutLcncod;
    }

    public void setPoutLcncod(String poutLcncod) {
        this.poutLcncod = poutLcncod;
    }

    public Integer getPoutDefFabseq() {
        return this.poutDefFabseq;
    }

    public void setPoutDefFabseq(Integer poutDefFabseq) {
        this.poutDefFabseq = poutDefFabseq;
    }

    public String getPoutDeffabdes() {
        return this.poutDeffabdes;
    }

    public void setPoutDeffabdes(String poutDeffabdes) {
        this.poutDeffabdes = poutDeffabdes;
    }

    public List<ProcFd723pk0placementDetailsResponsePoutRackbinList> getPoutRackbinList() {
        return this.poutRackbinList;
    }

    public void setPoutRackbinList(List<ProcFd723pk0placementDetailsResponsePoutRackbinList> poutRackbinList) {
        this.poutRackbinList = poutRackbinList;
    }

    public List<ProcFd723pk0placementDetailsResponsePoutFabseqlist> getPoutFabseqlist() {
        return this.poutFabseqlist;
    }

    public void setPoutFabseqlist(List<ProcFd723pk0placementDetailsResponsePoutFabseqlist> poutFabseqlist) {
        this.poutFabseqlist = poutFabseqlist;
    }

    public List<ProcFd723pk0placementDetailsResponsePoutDyejobList> getPoutDyejobList() {
        return this.poutDyejobList;
    }

    public void setPoutDyejobList(List<ProcFd723pk0placementDetailsResponsePoutDyejobList> poutDyejobList) {
        this.poutDyejobList = poutDyejobList;
    }

    public String getPoutDefDyejob() {
        return this.poutDefDyejob;
    }

    public void setPoutDefDyejob(String poutDefDyejob) {
        this.poutDefDyejob = poutDefDyejob;
    }

    public String getPoutMsg() {
        return this.poutMsg;
    }

    public void setPoutMsg(String poutMsg) {
        this.poutMsg = poutMsg;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcFd723pk0placementDetailsResponse)) return false;
        final ProcFd723pk0placementDetailsResponse procFd723pk0placementDetailsResponse = (ProcFd723pk0placementDetailsResponse) o;
        return Objects.equals(getPoutDyejobDet(), procFd723pk0placementDetailsResponse.getPoutDyejobDet()) &&
                Objects.equals(getPoutFabdet(), procFd723pk0placementDetailsResponse.getPoutFabdet()) &&
                Objects.equals(getPoutLcncod(), procFd723pk0placementDetailsResponse.getPoutLcncod()) &&
                Objects.equals(getPoutDefFabseq(), procFd723pk0placementDetailsResponse.getPoutDefFabseq()) &&
                Objects.equals(getPoutDeffabdes(), procFd723pk0placementDetailsResponse.getPoutDeffabdes()) &&
                Objects.equals(getPoutRackbinList(), procFd723pk0placementDetailsResponse.getPoutRackbinList()) &&
                Objects.equals(getPoutFabseqlist(), procFd723pk0placementDetailsResponse.getPoutFabseqlist()) &&
                Objects.equals(getPoutDyejobList(), procFd723pk0placementDetailsResponse.getPoutDyejobList()) &&
                Objects.equals(getPoutDefDyejob(), procFd723pk0placementDetailsResponse.getPoutDefDyejob()) &&
                Objects.equals(getPoutMsg(), procFd723pk0placementDetailsResponse.getPoutMsg());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutDyejobDet(),
                getPoutFabdet(),
                getPoutLcncod(),
                getPoutDefFabseq(),
                getPoutDeffabdes(),
                getPoutRackbinList(),
                getPoutFabseqlist(),
                getPoutDyejobList(),
                getPoutDefDyejob(),
                getPoutMsg());
    }
}