/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SprocFd107pk0CqprocGetRejCodResponse implements Serializable {


    @ColumnAlias("p_OutRejcodLOV")
    private List<SprocFd107pk0CqprocGetRejCodResponsePoutRejcodLov> poutRejcodLov;

    public List<SprocFd107pk0CqprocGetRejCodResponsePoutRejcodLov> getPoutRejcodLov() {
        return this.poutRejcodLov;
    }

    public void setPoutRejcodLov(List<SprocFd107pk0CqprocGetRejCodResponsePoutRejcodLov> poutRejcodLov) {
        this.poutRejcodLov = poutRejcodLov;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SprocFd107pk0CqprocGetRejCodResponse)) return false;
        final SprocFd107pk0CqprocGetRejCodResponse sprocFd107pk0cqprocGetRejCodResponse = (SprocFd107pk0CqprocGetRejCodResponse) o;
        return Objects.equals(getPoutRejcodLov(), sprocFd107pk0cqprocGetRejCodResponse.getPoutRejcodLov());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutRejcodLov());
    }
}