/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateProcFd1000wpk0ModjobUpdJobWeightRequest implements Serializable {


    @JsonProperty("pprgid")
    private String pprgid;

    @JsonProperty("pdyejob")
    private String pdyejob;

    @JsonProperty("pfabseq")
    private Integer pfabseq;

    @JsonProperty("pweight")
    private Integer pweight;

    public String getPprgid() {
        return this.pprgid;
    }

    public void setPprgid(String pprgid) {
        this.pprgid = pprgid;
    }

    public String getPdyejob() {
        return this.pdyejob;
    }

    public void setPdyejob(String pdyejob) {
        this.pdyejob = pdyejob;
    }

    public Integer getPfabseq() {
        return this.pfabseq;
    }

    public void setPfabseq(Integer pfabseq) {
        this.pfabseq = pfabseq;
    }

    public Integer getPweight() {
        return this.pweight;
    }

    public void setPweight(Integer pweight) {
        this.pweight = pweight;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UpdateProcFd1000wpk0ModjobUpdJobWeightRequest)) return false;
        final UpdateProcFd1000wpk0ModjobUpdJobWeightRequest updateProcFd1000wpk0modjobUpdJobWeightRequest = (UpdateProcFd1000wpk0ModjobUpdJobWeightRequest) o;
        return Objects.equals(getPprgid(), updateProcFd1000wpk0modjobUpdJobWeightRequest.getPprgid()) &&
                Objects.equals(getPdyejob(), updateProcFd1000wpk0modjobUpdJobWeightRequest.getPdyejob()) &&
                Objects.equals(getPfabseq(), updateProcFd1000wpk0modjobUpdJobWeightRequest.getPfabseq()) &&
                Objects.equals(getPweight(), updateProcFd1000wpk0modjobUpdJobWeightRequest.getPweight());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPprgid(),
                getPdyejob(),
                getPfabseq(),
                getPweight());
    }
}