/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateProcFd107pk0CqprocUpdInspectionStsRequest implements Serializable {


    @JsonProperty("p_usrid")
    private String pusrid;

    @JsonProperty("p_prgid")
    private String pprgid;

    @JsonProperty("p_cqsheetid")
    private String pcqsheetid;

    @JsonProperty("p_remarks")
    private String premarks;

    @JsonProperty("p_Mainsts")
    private String pmainsts;

    @JsonProperty("p_CondList")
    private String pcondList;

    @JsonProperty("p_Processlist")
    private String pprocesslist;

    @JsonProperty("p_rejectcod")
    private String prejectcod;

    public String getPusrid() {
        return this.pusrid;
    }

    public void setPusrid(String pusrid) {
        this.pusrid = pusrid;
    }

    public String getPprgid() {
        return this.pprgid;
    }

    public void setPprgid(String pprgid) {
        this.pprgid = pprgid;
    }

    public String getPcqsheetid() {
        return this.pcqsheetid;
    }

    public void setPcqsheetid(String pcqsheetid) {
        this.pcqsheetid = pcqsheetid;
    }

    public String getPremarks() {
        return this.premarks;
    }

    public void setPremarks(String premarks) {
        this.premarks = premarks;
    }

    public String getPmainsts() {
        return this.pmainsts;
    }

    public void setPmainsts(String pmainsts) {
        this.pmainsts = pmainsts;
    }

    public String getPcondList() {
        return this.pcondList;
    }

    public void setPcondList(String pcondList) {
        this.pcondList = pcondList;
    }

    public String getPprocesslist() {
        return this.pprocesslist;
    }

    public void setPprocesslist(String pprocesslist) {
        this.pprocesslist = pprocesslist;
    }

    public String getPrejectcod() {
        return this.prejectcod;
    }

    public void setPrejectcod(String prejectcod) {
        this.prejectcod = prejectcod;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UpdateProcFd107pk0CqprocUpdInspectionStsRequest)) return false;
        final UpdateProcFd107pk0CqprocUpdInspectionStsRequest updateProcFd107pk0cqprocUpdInspectionStsRequest = (UpdateProcFd107pk0CqprocUpdInspectionStsRequest) o;
        return Objects.equals(getPusrid(), updateProcFd107pk0cqprocUpdInspectionStsRequest.getPusrid()) &&
                Objects.equals(getPprgid(), updateProcFd107pk0cqprocUpdInspectionStsRequest.getPprgid()) &&
                Objects.equals(getPcqsheetid(), updateProcFd107pk0cqprocUpdInspectionStsRequest.getPcqsheetid()) &&
                Objects.equals(getPremarks(), updateProcFd107pk0cqprocUpdInspectionStsRequest.getPremarks()) &&
                Objects.equals(getPmainsts(), updateProcFd107pk0cqprocUpdInspectionStsRequest.getPmainsts()) &&
                Objects.equals(getPcondList(), updateProcFd107pk0cqprocUpdInspectionStsRequest.getPcondList()) &&
                Objects.equals(getPprocesslist(), updateProcFd107pk0cqprocUpdInspectionStsRequest.getPprocesslist()) &&
                Objects.equals(getPrejectcod(), updateProcFd107pk0cqprocUpdInspectionStsRequest.getPrejectcod());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPusrid(),
                getPprgid(),
                getPcqsheetid(),
                getPremarks(),
                getPmainsts(),
                getPcondList(),
                getPprocesslist(),
                getPrejectcod());
    }
}