/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateProcFd730wpk0UpdJobCountRequest implements Serializable {


    @JsonProperty("pPrgId")
    private String pprgId;

    @JsonProperty("pDDelNum")
    private String pddelNum;

    public String getPprgId() {
        return this.pprgId;
    }

    public void setPprgId(String pprgId) {
        this.pprgId = pprgId;
    }

    public String getPddelNum() {
        return this.pddelNum;
    }

    public void setPddelNum(String pddelNum) {
        this.pddelNum = pddelNum;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UpdateProcFd730wpk0UpdJobCountRequest)) return false;
        final UpdateProcFd730wpk0UpdJobCountRequest updateProcFd730wpk0updJobCountRequest = (UpdateProcFd730wpk0UpdJobCountRequest) o;
        return Objects.equals(getPprgId(), updateProcFd730wpk0updJobCountRequest.getPprgId()) &&
                Objects.equals(getPddelNum(), updateProcFd730wpk0updJobCountRequest.getPddelNum());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPprgId(),
                getPddelNum());
    }
}