/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class UpdateProcFd107pk0CqprocUpdInspectionStsResponse implements Serializable {


    @ColumnAlias("poutMsg")
    private String poutMsg;

    @ColumnAlias("p_fabupdated")
    private String pfabupdated;

    public String getPoutMsg() {
        return this.poutMsg;
    }

    public void setPoutMsg(String poutMsg) {
        this.poutMsg = poutMsg;
    }

    public String getPfabupdated() {
        return this.pfabupdated;
    }

    public void setPfabupdated(String pfabupdated) {
        this.pfabupdated = pfabupdated;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UpdateProcFd107pk0CqprocUpdInspectionStsResponse)) return false;
        final UpdateProcFd107pk0CqprocUpdInspectionStsResponse updateProcFd107pk0cqprocUpdInspectionStsResponse = (UpdateProcFd107pk0CqprocUpdInspectionStsResponse) o;
        return Objects.equals(getPoutMsg(), updateProcFd107pk0cqprocUpdInspectionStsResponse.getPoutMsg()) &&
                Objects.equals(getPfabupdated(), updateProcFd107pk0cqprocUpdInspectionStsResponse.getPfabupdated());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutMsg(),
                getPfabupdated());
    }
}