/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QrySignOffReldoubtDyeJobFabRouteResponse implements Serializable {


    @ColumnAlias("DYEJOB")
    private String dyejob;

    @ColumnAlias("REDYE")
    private Byte redye;

    @ColumnAlias("FABSEQ")
    private Byte fabseq;

    @ColumnAlias("PROCSEQ")
    private Short procseq;

    @ColumnAlias("SORTSEQ")
    private Byte sortseq;

    @ColumnAlias("SORTSUBSEQ")
    private String sortsubseq;

    @ColumnAlias("PROCESS")
    private String process;

    @ColumnAlias("SCNCOD")
    private String scncod;

    @ColumnAlias("OPTIND")
    private String optind;

    @ColumnAlias("ESTHRS")
    private LocalDateTime esthrs;

    @ColumnAlias("PROCSTS")
    private String procsts;

    @ColumnAlias("ACTDAT")
    private LocalDateTime actdat;

    @ColumnAlias("SCANMTS")
    private Double scanmts;

    @ColumnAlias("STARTDAT")
    private LocalDateTime startdat;

    @ColumnAlias("PROCSUBSTS")
    private String procsubsts;

    @ColumnAlias("POSTCQREQ")
    private String postcqreq;

    @ColumnAlias("SIGNOFFREM")
    private String signoffrem;

    @ColumnAlias("POSTCQCMPDAT")
    private LocalDateTime postcqcmpdat;

    public String getDyejob() {
        return this.dyejob;
    }

    public void setDyejob(String dyejob) {
        this.dyejob = dyejob;
    }

    public Byte getRedye() {
        return this.redye;
    }

    public void setRedye(Byte redye) {
        this.redye = redye;
    }

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    public Short getProcseq() {
        return this.procseq;
    }

    public void setProcseq(Short procseq) {
        this.procseq = procseq;
    }

    public Byte getSortseq() {
        return this.sortseq;
    }

    public void setSortseq(Byte sortseq) {
        this.sortseq = sortseq;
    }

    public String getSortsubseq() {
        return this.sortsubseq;
    }

    public void setSortsubseq(String sortsubseq) {
        this.sortsubseq = sortsubseq;
    }

    public String getProcess() {
        return this.process;
    }

    public void setProcess(String process) {
        this.process = process;
    }

    public String getScncod() {
        return this.scncod;
    }

    public void setScncod(String scncod) {
        this.scncod = scncod;
    }

    public String getOptind() {
        return this.optind;
    }

    public void setOptind(String optind) {
        this.optind = optind;
    }

    public LocalDateTime getEsthrs() {
        return this.esthrs;
    }

    public void setEsthrs(LocalDateTime esthrs) {
        this.esthrs = esthrs;
    }

    public String getProcsts() {
        return this.procsts;
    }

    public void setProcsts(String procsts) {
        this.procsts = procsts;
    }

    public LocalDateTime getActdat() {
        return this.actdat;
    }

    public void setActdat(LocalDateTime actdat) {
        this.actdat = actdat;
    }

    public Double getScanmts() {
        return this.scanmts;
    }

    public void setScanmts(Double scanmts) {
        this.scanmts = scanmts;
    }

    public LocalDateTime getStartdat() {
        return this.startdat;
    }

    public void setStartdat(LocalDateTime startdat) {
        this.startdat = startdat;
    }

    public String getProcsubsts() {
        return this.procsubsts;
    }

    public void setProcsubsts(String procsubsts) {
        this.procsubsts = procsubsts;
    }

    public String getPostcqreq() {
        return this.postcqreq;
    }

    public void setPostcqreq(String postcqreq) {
        this.postcqreq = postcqreq;
    }

    public String getSignoffrem() {
        return this.signoffrem;
    }

    public void setSignoffrem(String signoffrem) {
        this.signoffrem = signoffrem;
    }

    public LocalDateTime getPostcqcmpdat() {
        return this.postcqcmpdat;
    }

    public void setPostcqcmpdat(LocalDateTime postcqcmpdat) {
        this.postcqcmpdat = postcqcmpdat;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QrySignOffReldoubtDyeJobFabRouteResponse)) return false;
        final QrySignOffReldoubtDyeJobFabRouteResponse qrySignOffReldoubtDyeJobFabRouteResponse = (QrySignOffReldoubtDyeJobFabRouteResponse) o;
        return Objects.equals(getDyejob(), qrySignOffReldoubtDyeJobFabRouteResponse.getDyejob()) &&
                Objects.equals(getRedye(), qrySignOffReldoubtDyeJobFabRouteResponse.getRedye()) &&
                Objects.equals(getFabseq(), qrySignOffReldoubtDyeJobFabRouteResponse.getFabseq()) &&
                Objects.equals(getProcseq(), qrySignOffReldoubtDyeJobFabRouteResponse.getProcseq()) &&
                Objects.equals(getSortseq(), qrySignOffReldoubtDyeJobFabRouteResponse.getSortseq()) &&
                Objects.equals(getSortsubseq(), qrySignOffReldoubtDyeJobFabRouteResponse.getSortsubseq()) &&
                Objects.equals(getProcess(), qrySignOffReldoubtDyeJobFabRouteResponse.getProcess()) &&
                Objects.equals(getScncod(), qrySignOffReldoubtDyeJobFabRouteResponse.getScncod()) &&
                Objects.equals(getOptind(), qrySignOffReldoubtDyeJobFabRouteResponse.getOptind()) &&
                Objects.equals(getEsthrs(), qrySignOffReldoubtDyeJobFabRouteResponse.getEsthrs()) &&
                Objects.equals(getProcsts(), qrySignOffReldoubtDyeJobFabRouteResponse.getProcsts()) &&
                Objects.equals(getActdat(), qrySignOffReldoubtDyeJobFabRouteResponse.getActdat()) &&
                Objects.equals(getScanmts(), qrySignOffReldoubtDyeJobFabRouteResponse.getScanmts()) &&
                Objects.equals(getStartdat(), qrySignOffReldoubtDyeJobFabRouteResponse.getStartdat()) &&
                Objects.equals(getProcsubsts(), qrySignOffReldoubtDyeJobFabRouteResponse.getProcsubsts()) &&
                Objects.equals(getPostcqreq(), qrySignOffReldoubtDyeJobFabRouteResponse.getPostcqreq()) &&
                Objects.equals(getSignoffrem(), qrySignOffReldoubtDyeJobFabRouteResponse.getSignoffrem()) &&
                Objects.equals(getPostcqcmpdat(), qrySignOffReldoubtDyeJobFabRouteResponse.getPostcqcmpdat());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDyejob(),
                getRedye(),
                getFabseq(),
                getProcseq(),
                getSortseq(),
                getSortsubseq(),
                getProcess(),
                getScncod(),
                getOptind(),
                getEsthrs(),
                getProcsts(),
                getActdat(),
                getScanmts(),
                getStartdat(),
                getProcsubsts(),
                getPostcqreq(),
                getSignoffrem(),
                getPostcqcmpdat());
    }
}