/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QyProcessCqradioset2valuesResponse implements Serializable {


    @ColumnAlias("DISPLAYVALUE")
    private String displayvalue;

    @ColumnAlias("ITEMVALUE")
    private String itemvalue;

    public String getDisplayvalue() {
        return this.displayvalue;
    }

    public void setDisplayvalue(String displayvalue) {
        this.displayvalue = displayvalue;
    }

    public String getItemvalue() {
        return this.itemvalue;
    }

    public void setItemvalue(String itemvalue) {
        this.itemvalue = itemvalue;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QyProcessCqradioset2valuesResponse)) return false;
        final QyProcessCqradioset2valuesResponse qyProcessCqradioset2valuesResponse = (QyProcessCqradioset2valuesResponse) o;
        return Objects.equals(getDisplayvalue(), qyProcessCqradioset2valuesResponse.getDisplayvalue()) &&
                Objects.equals(getItemvalue(), qyProcessCqradioset2valuesResponse.getItemvalue());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDisplayvalue(),
                getItemvalue());
    }
}