/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.runtime.data.model.QueryProcedureInput;

import com.mu.cmt.pfs.pfsdb.models.query.*;

@Service
public class PfsdbQueryExecutorServiceImpl implements PfsdbQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(PfsdbQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("pfsdbWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "pfsdbTransactionManager")
    @Override
    public Integer executeQryDelDN(String pddelNum) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("pDDelNum", pddelNum);

        return queryExecutor.executeNamedQueryForUpdate("QryDelDN", params);
    }

    @Transactional(value = "pfsdbTransactionManager", readOnly = true)
    @Override
    public QryDefEmpcodeResponse executeQryDefEmpcode(String pusrid) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("p_usrid", pusrid);

        return queryExecutor.executeNamedQuery("QryDefEmpcode", params, QryDefEmpcodeResponse.class);
    }

    @Transactional(value = "pfsdbTransactionManager", readOnly = true)
    @Override
    public Page<QryDyejobFabRoutesResponse> executeQryDyejobFabRoutes(String dyejob, String fabseq, Pageable pageable) {
        Map<String, Object> params = new HashMap<>(2);

        params.put("dyejob", dyejob);
        params.put("fabseq", fabseq);

        return queryExecutor.executeNamedQuery("QryDyejobFabRoutes", params, QryDyejobFabRoutesResponse.class, pageable);
    }

    @Transactional(value = "pfsdbTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportQryDyejobFabRoutes(String dyejob, String fabseq, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(2);

        params.put("dyejob", dyejob);
        params.put("fabseq", fabseq);

        QueryProcedureInput queryInput = new QueryProcedureInput("QryDyejobFabRoutes", params, QryDyejobFabRoutesResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "pfsdbTransactionManager", readOnly = true)
    @Override
    public QrySy9200pk0callWmakerappResponse executeQrySy9200pk0CallWmakerapp(String pwmprogid, String pparamList) {
        Map<String, Object> params = new HashMap<>(2);

        params.put("pWmprogid", pwmprogid);
        params.put("pParamList", pparamList);

        return queryExecutor.executeNamedQuery("QrySy9200pk0CallWmakerapp", params, QrySy9200pk0callWmakerappResponse.class);
    }

    @Transactional(value = "pfsdbTransactionManager", readOnly = true)
    @Override
    public Page<QyProcessCqradioset2valuesResponse> executeQyProcessCQRadioset2Values(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("qyProcessCQRadioset2Values", params, QyProcessCqradioset2valuesResponse.class, pageable);
    }

    @Transactional(value = "pfsdbTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportQyProcessCQRadioset2Values(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput queryInput = new QueryProcedureInput("qyProcessCQRadioset2Values", params, QyProcessCqradioset2valuesResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "pfsdbTransactionManager", readOnly = true)
    @Override
    public Page<QyProcessCqradiosetValuesResponse> executeQyProcessCQRadiosetValues(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("qyProcessCQRadiosetValues", params, QyProcessCqradiosetValuesResponse.class, pageable);
    }

    @Transactional(value = "pfsdbTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportQyProcessCQRadiosetValues(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput queryInput = new QueryProcedureInput("qyProcessCQRadiosetValues", params, QyProcessCqradiosetValuesResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "pfsdbTransactionManager", readOnly = true)
    @Override
    public Page<QrySignOffReldoubtDyeJobFabRouteResponse> executeQrySignOffReldoubtDyeJobFabRoute(String dyejob, Integer fabseq, Pageable pageable) {
        Map<String, Object> params = new HashMap<>(2);

        params.put("dyejob", dyejob);
        params.put("fabseq", fabseq);

        return queryExecutor.executeNamedQuery("QrySignOffReldoubtDyeJobFabRoute", params, QrySignOffReldoubtDyeJobFabRouteResponse.class, pageable);
    }

    @Transactional(value = "pfsdbTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportQrySignOffReldoubtDyeJobFabRoute(String dyejob, Integer fabseq, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(2);

        params.put("dyejob", dyejob);
        params.put("fabseq", fabseq);

        QueryProcedureInput queryInput = new QueryProcedureInput("QrySignOffReldoubtDyeJobFabRoute", params, QrySignOffReldoubtDyeJobFabRouteResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "pfsdbTransactionManager", readOnly = true)
    @Override
    public Page<QryEmployeeCodeSignOffResponse> executeQryEmployeeCodeSignOff(String pusrid, Pageable pageable) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("p_usrid", pusrid);

        return queryExecutor.executeNamedQuery("QryEmployeeCodeSignOff", params, QryEmployeeCodeSignOffResponse.class, pageable);
    }

    @Transactional(value = "pfsdbTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportQryEmployeeCodeSignOff(String pusrid, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("p_usrid", pusrid);

        QueryProcedureInput queryInput = new QueryProcedureInput("QryEmployeeCodeSignOff", params, QryEmployeeCodeSignOffResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "pfsdbTransactionManager", readOnly = true)
    @Override
    public Page<QryFabseqLovResponse> executeQryFabseqLOV(String pdyejob, Pageable pageable) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("pdyejob", pdyejob);

        return queryExecutor.executeNamedQuery("QryFabseqLOV", params, QryFabseqLovResponse.class, pageable);
    }

    @Transactional(value = "pfsdbTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportQryFabseqLOV(String pdyejob, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("pdyejob", pdyejob);

        QueryProcedureInput queryInput = new QueryProcedureInput("QryFabseqLOV", params, QryFabseqLovResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "pfsdbTransactionManager", readOnly = true)
    @Override
    public Page<QrySignOffRejectDyeJobFabRouteResponse> executeQrySignOffRejectDyeJobFabRoute(String dyejob, Integer fabseq, Pageable pageable) {
        Map<String, Object> params = new HashMap<>(2);

        params.put("dyejob", dyejob);
        params.put("fabseq", fabseq);

        return queryExecutor.executeNamedQuery("QrySignOffRejectDyeJobFabRoute", params, QrySignOffRejectDyeJobFabRouteResponse.class, pageable);
    }

    @Transactional(value = "pfsdbTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportQrySignOffRejectDyeJobFabRoute(String dyejob, Integer fabseq, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(2);

        params.put("dyejob", dyejob);
        params.put("fabseq", fabseq);

        QueryProcedureInput queryInput = new QueryProcedureInput("QrySignOffRejectDyeJobFabRoute", params, QrySignOffRejectDyeJobFabRouteResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "pfsdbTransactionManager", readOnly = true)
    @Override
    public QryCheckEmpcodeResponse executeQryCheckEmpcode(String pusrid) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("p_usrid", pusrid);

        return queryExecutor.executeNamedQuery("QryCheckEmpcode", params, QryCheckEmpcodeResponse.class);
    }

}